export const AUTH_SLICE = 'auth'
export const ACTIVATE_SLICE = 'activate'
export const PERSONAL_SLICE = 'personal'
export const RESET_SLICE = 'reset'
export const PREMIUM_SLICE = 'premium'
export const PREMIUM_BUY_SLICE = 'premium-buy'
export const PREMIUM_LOGIN_SLICE = 'premium-login'
export const PREMIUM_PAYMENT_FAILED_SLICE = 'premium-payment-failed'
