services:
  turi-db:
    container_name: turi-db
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: turi
      POSTGRES_USER: turi
      POSTGRES_PASSWORD: turi-db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./turi-db/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
