server:
    port: 8080

spring:
    web:
        resources:
            static-locations: file:./uploads/
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/turi}
        username: ${SPRING_DATASOURCE_USERNAME:turi}
        password: ${SPRING_DATASOURCE_PASSWORD:turi-db}
        driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: false
                show_sql: false
        show_sql: false
        open-in-view: false
    mail:
        host: smtp.gmail.com
        port: 587
        username: noreply.turi@gmail.com
        password:
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

security:
    jwt:
        secret-key:
        access-token-expiration-time: 900
        refresh-token-expiration-time: 604800

springdoc:
    swagger-ui:
        enabled: true
        path: /swagger-ui

stripe:
    secret-key:
    success-url: http://localhost:3000/premium/payment-check
    cancel-url: http://localhost:3000/premium/payment
    webhook-secret-key:

premium:
    price: 100
    length: 12

ceidg:
    url: https://dane.biznes.gov.pl/api/ceidg/v3/firmy
    api-key:

image:
    storage:
        mode: local
        path: ./uploads/
        local-url: http://localhost:8080/uploads/
        azure-url:

azure:
    storage:
        account-name:
        account-key:
        container-name:
