server:
    port: 8080

spring:
    web:
        resources:
            static-locations: file:./uploads/
    datasource:
        url: jdbc:postgresql://${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: false
                show_sql: false
        show_sql: false
        open-in-view: false
    mail:
        host: smtp.gmail.com
        port: 587
        username: noreply.turi@gmail.com
        password: huvmxzbezwqeinul
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                    ssl.trust: smtp.gmail.com

security:
    jwt:
        secret-key: ${SECRET_KEY}
        access-token-expiration-time: 900
        refresh-token-expiration-time: 604800

ui:
    url: ${UI_URL}

springdoc:
    swagger-ui:
        enabled: true
        path: /swagger-ui

stripe:
    secret-key: ${STRIPE_SECRET_KEY}
    webhook-secret-key: ${WEBHOOK_SECRET_KEY}
    premium-success-url: ${UI_URL}/premium/payment-check
    premium-cancel-url: ${UI_URL}/premium/payment
    reservation-success-url: ${UI_URL}/reservation/payment-check
    reservation-cancel-url: ${UI_URL}/reservation/payment

premium:
    price: 100
    length: 12

ceidg:
    url: https://dane.biznes.gov.pl/api/ceidg/v3/firmy
    api-key: ${CEIDG_API_KEY}

image:
    storage:
        mode: ${IMAGE_STORAGE_MODE}
        path: ./uploads/
        local-url: http://localhost:8080/uploads/
        azure-url: ${IMAGE_STORAGE_AZURE_URL}

azure:
    storage:
        account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
        account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
        container-name: ${AZURE_STORAGE_CONTAINER_NAME}
