server:
    port: 8080

spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/turi}
        username: ${SPRING_DATASOURCE_USERNAME:turi}
        password: ${SPRING_DATASOURCE_PASSWORD:turi-db}
        driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: false
                show_sql: false
        show_sql: false
        open-in-view: false

security:
    jwt:
        secret-key: 7bfe24ef14214c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
        expiration-time: 86400000

springdoc:
    swagger-ui:
        enabled: true
        path: /