server:
    port: 8080

spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/turi}
        username: ${SPRING_DATASOURCE_USERNAME:turi}
        password: ${SPRING_DATASOURCE_PASSWORD:turi-db}
        driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: false
                show_sql: false
        show_sql: false
        open-in-view: false
    mail:
        host: smtp.gmail.com
        port: 587
        username: noreply.turi@gmail.com
        password: zrpuiuyahtqpppsb
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

security:
    jwt:
        secret-key: 7bfe24ef14214c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
        access-token-expiration-time: 900
        refresh-token-expiration-time: 604800

springdoc:
    swagger-ui:
        enabled: true
        path: /swagger-ui

stripe:
    secret-key: sk_test_51QQXh7CSCKL1O9vwSd4Kbrv52qCCUQXSvAEDqBcQ8NQUjq9KRo33EdoN1yhPgknfceJKrNK4xlQEqJgcb0DxiHUk00XFVchD2I
    success-url: http://localhost:8080/premium/payment-check
    cancel-url: http://localhost:8080/premium/payment
    webhook-secret-key: whsec_44044973b8d5c9ca85880298170c6461d14a2b68bcff6e41d0c0d9e8b1979f18

premium:
    offer:
        price: 100
        length: 12