name: Build and deploy JAR app to Azure Web App - turi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Make gradlew executable
        run: cd turi && chmod +x gradlew

      - name: Build with Gradle
        run: cd turi && ./gradlew bootJar

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: turi/build/libs/app.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_132B8F3D94B344CD8AD43DED433B36E7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_87FD9ADD770A4B9DBF0B2616C709E157 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BB31267E284E4E7084B28AC79D4529E9 }}

      - name: Environment variables
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> $GITHUB_ENV
          echo "WEBHOOK_SECRET_KEY=${{ secrets.WEBHOOK_SECRET_KEY }}" >> $GITHUB_ENV
          echo "UI_URL=${{ secrets.UI_URL }}" >> $GITHUB_ENV
          echo "CEIDG_API_KEY=${{ secrets.CEIDG_API_KEY }}" >> $GITHUB_ENV
          echo "IMAGE_STORAGE_MODE=${{ secrets.IMAGE_STORAGE_MODE }}" >> $GITHUB_ENV
          echo "IMAGE_STORAGE_AZURE_URL=${{ secrets.IMAGE_STORAGE_AZURE_URL }}" >> $GITHUB_ENV
          echo "AZURE_STORAGE_ACCOUNT_NAME=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_ENV
          echo "AZURE_STORAGE_ACCOUNT_KEY=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" >> $GITHUB_ENV
          echo "AZURE_STORAGE_CONTAINER_NAME=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}" >> $GITHUB_ENV

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'turi'
          slot-name: 'Production'
          package: '*.jar'
